FROM python:3.11-slim AS build

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY guess/ ./guess
COPY repository/ ./repository
COPY .env .
COPY run.py .
#COPY . .

ENV FLASK_APP=run.py
EXPOSE 3000

CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=3000"]