version: "3.8"

services:
  guess-game-frontend:
    image: emanuelbrodrigues/emanuelbrodrigues-orqcontainer-guessgame-frontend:1
    container_name: guess-game-frontend
    restart: always
    environment:
      REACT_APP_BACKEND_URL: http://192.168.0.206:2600
    ports:
      - 1800:80
    depends_on:
      - guess-game-backend

  guess-game-backend:
    image: emanuelbrodrigues/emanuelbrodrigues-orqcontainer-guessgame-backend:1
    container_name: guess-game-backend
    restart: always
    environment:
      FLASK_DB_TYPE: postgres
      FLASK_DB_USER: postgres
      FLASK_DB_NAME: mydatabase
      FLASK_DB_PASSWORD: password
      FLASK_DB_HOST: 192.168.0.206
      FLASK_DB_PORT: 5132
    ports:
      - 2600:3000
    depends_on:
      - guess-game-database
      
  guess-game-database:
    image: postgres:15.3-alpine
    container_name: guess-game-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - 5132:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: