version: "3.8"

services:
  guess-game-frontend-1:
    image: emanuelbrodrigues/emanuelbrodrigues-orqcontainer-guessgame-frontend:1
    container_name: guess-game-frontend-1
    restart: on-failure
    environment:
      REACT_APP_BACKEND_URL: http://localhost:9090
    depends_on:
      - guess-game-nginx
    ports:
      - "8080:80"  

  guess-game-backend-1:
    image: emanuelbrodrigues/emanuelbrodrigues-orqcontainer-guessgame-backend:1
    container_name: guess-game-backend-1
    restart: on-failure
    environment:
      FLASK_DB_TYPE: postgres
      FLASK_DB_USER: postgres
      FLASK_DB_NAME: mydatabase
      FLASK_DB_PASSWORD: password
      FLASK_DB_HOST: guess-game-database
      FLASK_DB_PORT: 5432
    expose:
      - "3000"
    depends_on:
      - guess-game-database

  guess-game-backend-2:
    image: emanuelbrodrigues/emanuelbrodrigues-orqcontainer-guessgame-backend:1
    container_name: guess-game-backend-2
    restart: on-failure
    environment:
      FLASK_DB_TYPE: postgres
      FLASK_DB_USER: postgres
      FLASK_DB_NAME: mydatabase
      FLASK_DB_PASSWORD: password
      FLASK_DB_HOST: guess-game-database
      FLASK_DB_PORT: 5432
    expose:
      - "3000"
    depends_on:
      - guess-game-database

  guess-game-database:
    image: postgres:15.3-alpine
    container_name: guess-game-database
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data

  guess-game-nginx:
    image: nginx:alpine
    container_name: guess-game-nginx
    restart: on-failure
    ports:
      - "9090:80"
    volumes:
      - ./configuracao-nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - guess-game-backend-1
      - guess-game-backend-2

volumes:
  postgres-data:
