FROM node:18.17.0-alpine as build

WORKDIR /app

COPY public ./public
COPY src ./src
COPY package.json ./
COPY .env ./env
COPY cypress.config.ts ./
COPY default.conf ./
COPY jest.config.ts ./
COPY package.json ./
COPY tsconfig.json ./

RUN corepack enable

RUN npm install

ENV PORT=80
EXPOSE 80
CMD ["yarn", "start"]